import ImageComponent from "@/components/ImageComponent";
import "../globals.css";
import { Plus_Jakarta_Sans } from "next/font/google";
import "react-toastify/dist/ReactToastify.css";
import { ToastContainer } from "react-toastify";
import NextTopLoader from "nextjs-toploader";

const jakarta = Plus_Jakarta_Sans({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={jakarta.className}>
        <ToastContainer />
        <NextTopLoader
          color="#98a2b3"
          initialPosition={0.08}
          crawlSpeed={300}
          height={3}
          crawl={true}
          showSpinner={false}
          easing="ease"
          speed={200}
          shadow="0 0 10px #344054,0 0 8px #344054"
        />
        <div className="grid grid-cols-1 md:grid-cols-[1fr_2fr] h-screen px-6 py-6 bg-white">
          <div className="hidden overflow-hidden md:flex items-end justify-center p-4 md:p-10 bg-primaryCherUi relative rounded-3xl">
            <ImageComponent />
          </div>
          <div className="flex justify-center items-center md:items-start mt-12 px-8 md:px-20">
            <div className="w-full max-w-lg">{children}</div>
          </div>
        </div>
      </body>
    </html>
  );
}
