import "../../globals.css";
import { Plus_Jakarta_Sans } from "next/font/google";
import { StepperDamnV2 } from "@/components/alternative/StepperV2";
import NextTopLoader from "nextjs-toploader";

const jakarta = Plus_Jakarta_Sans({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  // return (
  //   <div className={`h-full w-full${jakarta.className}`}>
  //     <StepperDamnV2 className={"mt-8 lg:mt-32"} />
  //     <div className="mt-16 lg:mt-32">{children}</div>
  //   </div>
  // );
  return (
    <>
      <NextTopLoader
        color="#98a2b3"
        initialPosition={0.08}
        crawlSpeed={300}
        height={3}
        crawl={true}
        showSpinner={false}
        easing="ease"
        speed={200}
        shadow="0 0 10px #344054,0 0 8px #344054"

      />
      <div className={`h-full w-full${jakarta.className}`}>
        <StepperDamnV2 className={"mt-8 lg:mt-32"} />
        <div className="mt-12 lg:mt-20 flex justify-center items-center">
          {children}
        </div>
      </div>
    </>
  );
}
